CREATE TABLE IF NOT EXISTS users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL CHECK (username <> ''),
    email text NOT NULL UNIQUE,  
    password text NOT NULL,
    phone text,
    company text,
    image bytea
    
);



-- Insert Users

INSERT INTO users(username, email, password) VALUES('Paolo Guerrero', 'paolo@gmail.com', 'paolo123');
INSERT INTO users(username, email, password) VALUES('Pedro Aquino', 'pedro@gmail.com', 'pedro123');



