CREATE TABLE IF NOT EXISTS users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL CHECK (username <> ''),
    email text NOT NULL UNIQUE,  
    password text NOT NULL
    
);

CREATE TABLE IF NOT EXISTS profiles (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image bytea,
    phone text,    
    company text,
    userid INTEGER UNIQUE REFERENCES users(id)

);

-- Insert Users

INSERT INTO users(username, email, password) VALUES('Paolo Guerrero', 'paolo@gmail.com', 'paolo123');
INSERT INTO users(username, email, password) VALUES('Pedro Aquino', 'pedro@gmail.com', 'pedro123');

