CREATE TABLE IF NOT EXISTS Usuario (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL CHECK (username <> ''),
    uerlastname text NOT NULL CHECK (username <> ''),
    email text NOT NULL UNIQUE,  
    password text NOT NULL,    
    imagen text,
    telefono text,
    empresa text,
    instagram_link text,
    facebook_link text,
    twitter_link text,
    wallet_address text
    
);

CREATE TABLE IF NOT EXISTS Rol (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rolename text NOT NULL CHECK (rolname)
    userId = integer NOT NULL
    CONSTRAINT fk_usuario FOREIGN KEY(usuario_id) REFERENCES usuario(id)
); 






